#!/bin/bash

set -euf -o pipefail

source "/etc/lsb-release"
source "etc/project-data"

version="$1"
release=$(lsb_release --codename --short)
package="$name-$version-$release"

cargo build --release

rm -rf "work/$package"
mkdir -p "work/$package"

for content in "${contents[@]}"; do
	cp "target/release/$content" "work/$package/$content"
done

tar \
	--create \
	--xz \
	--directory "work" \
	--file "work/$package.tar.xz" \
	"$package"

scp \
	"work/$package.tar.xz" \
	"$target/$package.tar.xz"

# ex: noet ts=4 filetype=sh
